package FINAL_GAME;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

import Dependencias.Imagen;

/**
 *
 * @author ChiquitoS11
 */
public class JuegoMenu extends javax.swing.JFrame {
    
    // icono taskbar
    private final Imagen iconoWindows = new Imagen(getClass().getResource("/resources/iconoWindows.jpg"));
    
    // redes sociales
    private final Imagen ghImg = new Imagen(getClass().getResource("/resources/githubIcon.png"));
    private final Imagen igImg = new Imagen(getClass().getResource("/resources/instagramIcon.png"));
    
    // cerrar
    private final Imagen btnCerrarImg = new Imagen(getClass().getResource("/resources/btnCerrarFrame.png"));
    
    // fondo de pantalla
    private final Imagen fp = new Imagen(getClass().getResource("/resources/fondoMenu.gif"));
    
    /**
     * Creates new form JuegoMenu
     */
    public JuegoMenu() {
        this.setContentPane(fp);  
        
        initComponents();
        
        
        ajustesVisuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        GitHubLabel = new javax.swing.JLabel();
        InstagramLabel = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GitHubLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GitHubLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GitHubLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GitHubLabelMouseExited(evt);
            }
        });

        InstagramLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstagramLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstagramLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InstagramLabelMouseExited(evt);
            }
        });

        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InstagramLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(700, 700, 700)
                        .addComponent(jButton1))
                    .addComponent(GitHubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(InstagramLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GitHubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajustesVisuales(){
        this.setIconImage(iconoWindows.getImagenIMAGE());
        
        GitHubLabel.setIcon(ghImg.imgToContainer(GitHubLabel));
        InstagramLabel.setIcon(igImg.imgToContainer(InstagramLabel));
        btnCerrar.setIcon(btnCerrarImg.imgToContainer(btnCerrar));

        
        repaint();
    }
    
    private void GitHubLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GitHubLabelMouseClicked
        abrirEnlace("https://github.com/ChiquitoS11");
    }//GEN-LAST:event_GitHubLabelMouseClicked
    private void InstagramLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstagramLabelMouseClicked
        abrirEnlace("https://www.instagram.com/joshuahasproblems/");
    }//GEN-LAST:event_InstagramLabelMouseClicked

    private void GitHubLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GitHubLabelMouseEntered

        GitHubLabel.setIcon(ghImg.cambiarOpacidad(0.5f, GitHubLabel));
        
        repaint();
    }//GEN-LAST:event_GitHubLabelMouseEntered
    private void GitHubLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GitHubLabelMouseExited
        
        GitHubLabel.setIcon(ghImg.imgToContainer(GitHubLabel));        

        repaint();
    }//GEN-LAST:event_GitHubLabelMouseExited
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JuegoChooseCharacter jcc = new JuegoChooseCharacter(this);
        jcc.setVisible(true);
        jcc.setResizable(false);
        jcc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void InstagramLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstagramLabelMouseEntered
        InstagramLabel.setIcon(ghImg.cambiarOpacidad(0.5f, InstagramLabel));
        
        repaint();
    }//GEN-LAST:event_InstagramLabelMouseEntered
    private void InstagramLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstagramLabelMouseExited
        InstagramLabel.setIcon(igImg.imgToContainer(InstagramLabel));        
        
        repaint();
    }//GEN-LAST:event_InstagramLabelMouseExited

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked
    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setIcon(btnCerrarImg.cambiarOpacidad(0.5f, btnCerrar));
        
        repaint();
    }//GEN-LAST:event_btnCerrarMouseEntered
    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        btnCerrar.setIcon(btnCerrarImg.imgToContainer(btnCerrar));        
        
        repaint();
    }//GEN-LAST:event_btnCerrarMouseExited
    
    private void abrirEnlace(String enlace) {
        try{
            if (Desktop.isDesktopSupported()) {
                Desktop ordenador = Desktop.getDesktop();
                if (ordenador.isSupported(Desktop.Action.BROWSE)) {
                    ordenador.browse(new URI(enlace));
                }
            }
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel GitHubLabel;
    public javax.swing.JLabel InstagramLabel;
    private javax.swing.JLabel btnCerrar;
    public javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
