package FINAL_GAME;

import Clases.Personaje;
import Dependencias.Imagen;
import java.awt.event.KeyEvent;


/**
 *
 * @author ChiquitoS11
 */
public class Juego extends javax.swing.JFrame {
    boolean activarSecreto = false;
    
    // icono taskbar
    private final Imagen taskbarIMG = new Imagen(getClass().getResource("/resources/iconoWindows.jpg"));
    
    Personaje mainCharacter = new Personaje(this);
    Imagen mainCharacterImg = new Imagen(getClass().getResource("/resources/ISAAC.png"));
    Imagen fondoImg = new Imagen(getClass().getResource("/resources/fondoChooseCharacter.gif"));
    
        
    public Juego(JuegoChooseCharacter jcc) {
        this.setContentPane(fondoImg);
        
        initComponents();
        
        ajustesVisuales();
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personajeLabel = new javax.swing.JLabel();
        abrirPuerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        personajeLabel.setLabelFor(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(personajeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(abrirPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(720, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(personajeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(abrirPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        personajeLabel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (mainCharacter.getX() >= abrirPuerta.getX() &&  mainCharacter.getX() <= (abrirPuerta.getX() + abrirPuerta.getWidth()) &&
                 mainCharacter.getY() >= abrirPuerta.getY() &&  mainCharacter.getY() <= (abrirPuerta.getY() + abrirPuerta.getHeight())) {
            activarSecreto = true;
        } else {
            activarSecreto = false;
        }
//        if (evt.getKeyCode()==KeyEvent.VK_W && evt.getKeyCode()==KeyEvent.VK_A) {
//            mainCharacter.moverArriba();
//            mainCharacter.moverIzquierda();
//        }
        
        if (evt.getKeyCode()==KeyEvent.VK_W) {
            mainCharacter.moverArriba();
        }
        if (evt.getKeyCode()==KeyEvent.VK_S) {
            mainCharacter.moverAbajo();
        }
        if (evt.getKeyCode()==KeyEvent.VK_A) {
            mainCharacter.moverIzquierda();
        }
        if (evt.getKeyCode()==KeyEvent.VK_D) {
            mainCharacter.moverDerecha();
        }

        System.out.println(activarSecreto);
    }//GEN-LAST:event_formKeyPressed

    public void ajustesVisuales(){
        this.setIconImage(taskbarIMG.getImagenIMAGE());
        
        personajeLabel.setIcon(mainCharacterImg.imgToContainer(personajeLabel)); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel abrirPuerta;
    public javax.swing.JLabel personajeLabel;
    // End of variables declaration//GEN-END:variables
}

